name: Test Docker Workflow

on:
  push:
    branches:
      - '*"

jobs:
  docker-test:
    runs-on: self-hosted
    container:
      image: docker:stable
    steps:
      - name: Check Docker Version
        run: docker version

      - name: Run Hello-World Container
        run: docker run hello-world
