name: Test Docker Workflow

on:
  push:          # Trigger on pushes to any branch
  pull_request:  # Trigger on pull requests to any branch

jobs:
  docker-test:
    runs-on: self-hosted
    container:
      image: docker:stable
    steps:
      - name: Check Docker Version
        run: docker version

      - name: Run Hello-World Container
        run: docker run hello-world

  host-test: # New job running directly on the host
    runs-on: self-hosted
    steps:
      - name: Print Hello
        run: echo "Hello from the host!"

      - name: Wait for 1 minute
        run: sleep 60

      - name: Print Exiting
        run: echo "Exiting..."
