name: Echo and Wait Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  echo-job:
    runs-on: self-hosted
    steps:
      - name: Echo Start
        run: echo "Pipeline has started"

      - name: Wait for 1 Minute
        run: sleep 60

      - name: Echo End
        run: echo "Pipeline has finished"
